name: Matrix demo
on:
    push:
        branches:
            - main
run-name: matrix job
jobs:
    build:
        strategy:
            matrix:
                python-version: [3.09, 3.10, 3.13]
                operating-system: ["ubuntu-latest", "windows-latest"]
                include: # This combination will be included additionally
                    - python-version: 3.12
                      operating-system: ubuntu-latest
                    - python-version: 3.08
                      operating-system: ubuntu-latest
                exclude: # This combination will be excluded
                    - python-version: 3.10
                      operating-system: windows-latest
                    - python-version: 3.09
                      operating-system: windows-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install python
              uses: actions/checkout@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install packages
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run python script
              run: |
                ls -lrt